# Base image
FROM python:3.9-slim

# DONE: Set the working directory to /app
WORKDIR /app

# DONE: Copy the requirements.txt file to the working directory
COPY requirements.txt .

# DONE: Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# DONE: Copy the training script (train.py) to the working directory
COPY train.py .

# DONE: Run the training script that generates the model
CMD ["python", "train.py"]
